wso2/common-terraform-modules

.github/workflows/tffmt.yml
.github/workflows/tflinter.yml
.github/workflows/trivy.yml
.gitignore
modules/local/Local-File/local-file.tf
modules/local/Local-File/locals.tf
modules/local/Local-File/variables.tf
modules/local/Local-File/versions.tf
modules/random/Random-Password/outputs.tf
modules/random/Random-Password/password.tf
modules/random/Random-Password/variables.tf
modules/random/Random-Password/versions.tf
modules/tls/SSH-Key-Pair/key_pair.tf
modules/tls/SSH-Key-Pair/outputs.tf
modules/tls/SSH-Key-Pair/variables.tf
modules/tls/SSH-Key-Pair/versions.tf
modules/tls/Self-Signed-Cert-Key-Pair-EDSCA/cert.tf
modules/tls/Self-Signed-Cert-Key-Pair-EDSCA/outputs.tf
modules/tls/Self-Signed-Cert-Key-Pair-EDSCA/variables.tf
modules/tls/Self-Signed-Cert-Key-Pair-EDSCA/versions.tf
modules/tls/Self-Signed-Cert-Key-Pair-RSA/cert.tf
modules/tls/Self-Signed-Cert-Key-Pair-RSA/outputs.tf
modules/tls/Self-Signed-Cert-Key-Pair-RSA/variables.tf
modules/tls/Self-Signed-Cert-Key-Pair-RSA/versions.tf

This PR adds modules from the following providers
- Random
- Random Password 
- TLS
- SSH Key
- Self Signed Cert RSA
- Self Signed Cert EDSCA
- Local
- Local Files

Add initial modules

---

modules/random/Random-Password/versions.tf

Update versions of the Random Password module

---

modules/random/Random-Password/password.tf
modules/random/Random-Password/variables.tf

Provide option to enable special characters

---

modules/random/Random-UUID/outputs.tf
modules/random/Random-UUID/uuid.tf
modules/random/Random-UUID/versions.tf

> Create a new Random UUID module using the `Hashicorp/random/uuid` resource.

Create new Random-UUID module

---

modules/opensearch/Monitor/monitor.tf
modules/opensearch/Monitor/variables.tf
modules/opensearch/Monitor/versions.tf

Creating terraform modules for open search monitor for log alerts.
> Describe the solutions that this feature/fix will introduce to resolve the problems described above
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.
> Summary of user stories addressed by this change>
> Brief description of the new feature or bug fix as it will appear in the release notes
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in …

Changes added with Open Search monitor TF configs

---

.github/workflows/trivy.yml
modules/github/Github-Actions-Secret/action_secret.tf
modules/github/Github-Actions-Secret/locals.tf
modules/github/Github-Actions-Secret/variables.tf
modules/github/Github-Actions-Secret/versions.tf
modules/github/Github-Actions-Variable/action_variable.tf
modules/github/Github-Actions-Variable/locals.tf
modules/github/Github-Actions-Variable/variables.tf
modules/github/Github-Actions-Variable/versions.tf

This pull request adds reusable Terraform modules to manage GitHub Actions secrets and variables using the GitHub provider. 
- `action_secret.tf`: Defines the `github_actions_secret` resource for securely managing repository secrets.
- `locals.tf`: Contains default values and internal logic.
- `variables.tf`: Declares required and optional inputs for flexibility.
- `versions.tf`: Locks provider and Terraform versions to ensure compatibility.
- `action_variable.tf`: Defines the `github_actions_variable` resource for managing repository-level variables.
- `locals.tf`: Internal helpers for cleaner configuration.
- `variables.tf`: Module interface to support custom input.
- `versions.tf`: Ensures consistent behavior across environments.

Introduce GitHub Provider Modules for Actions Secrets and Variables

---

modules/github/Github-Environment-Policy/github_environment_policy.tf
modules/github/Github-Environment-Policy/locals.tf
modules/github/Github-Environment-Policy/variables.tf
modules/github/Github-Environment-Policy/versions.tf
modules/github/Github-Environment-Secret/github_environment_secret.tf
modules/github/Github-Environment-Secret/locals.tf
modules/github/Github-Environment-Secret/variables.tf
modules/github/Github-Environment-Secret/versions.tf
modules/github/Github-Environment-Variable/github_environment_variable.tf
modules/github/Github-Environment-Variable/locals.tf
modules/github/Github-Environment-Variable/variables.tf
modules/github/Github-Environment-Variable/versions.tf
modules/github/Github-Repository-Environment/github_environment.tf
modules/github/Github-Repository-Environment/locals.tf
modules/github/Github-Repository-Environment/variables.tf
modules/github/Github-Repository-Environment/versions.tf
modules/github/Github-Repository-File/locals.tf
modules/github/Github-Repository-File/repository_file.tf
modules/github/Github-Repository-File/variables.tf
modules/github/Github-Repository-File/versions.tf

Introduce reusable Terraform modules for managing GitHub repository environments and GitHub files.
- Added `Github-Repository-File` module:
- Manages repository files using Terraform.
- Added GitHub environment-related modules:
- `Github-Environment-Policy`
- `Github-Environment-Secret`
- `Github-Environment-Variable`
- `Github-Repository-Environment`
Each module includes:
- Resource definitions (`.tf` files)
- Input variables
- Version constraints
- Local configurations for better reusability

Introduce github environment & github repository file modules

---

modules/helm/Helm-Release/helm_release.tf
modules/helm/Helm-Release/variables.tf
modules/helm/Helm-Release/versions.tf
modules/kubernetes/Secrets/namespace.tf

* Fix bug in Helm Release module

Fix issues in Helm Modules

---

modules/helm/Helm-Release/helm_release.tf
modules/helm/Helm-Release/variables.tf

* Missing namespace parameter to Helm Release

Add namespace to helm release

---

modules/kubernetes/ConfigMap/namespace.tf
modules/kubernetes/ConfigMap/variables.tf
modules/kubernetes/ConfigMap/versions.tf

Add Configmap

---

modules/helm/Helm-Release/helm_release.tf
modules/helm/Helm-Release/variables.tf

Update install param to Helm

---

modules/flux/Flux-Deployment/flux_deployment.tf
modules/flux/Flux-Deployment/variables.tf

Update image pull secret

---

modules/flux/Flux-Deployment/flux_deployment.tf
modules/flux/Flux-Deployment/variables.tf
modules/kubernetes/StorageClass/storageclass.tf
modules/kubernetes/StorageClass/variables.tf
modules/kubernetes/StorageClass/versions.tf
modules/postgresql/PostgreSQL-Database/database.tf
modules/postgresql/PostgreSQL-Database/variables.tf
modules/postgresql/PostgreSQL-Database/versions.tf
modules/vault/Kubernetes-Secret/secret.tf
modules/vault/Kubernetes-Secret/variables.tf

* Add Modules for StorageClass in K8S
* Add modules for DBs in PostgreSQL

Add Storage class module

---

modules/vault/Kubernetes-Secret/secret.tf
modules/vault/Kubernetes-Secret/variables.tf

* Remove faulty provider in Terraform

Update Vault Policy

---

modules/vault/Kubernetes-Auth/vault.tf
modules/vault/Kubernetes-Auth/versions.tf
modules/vault/Kubernetes-Secret/secret.tf

Create backend auth module

---

modules/vault/Kubernetes-Auth/vault.tf
modules/vault/Kubernetes-Secret/secret.tf

Fix secret name in terraform

---

modules/helm/Helm-Release/helm_release.tf
modules/helm/Helm-Release/variables.tf
modules/postgresql/PostgreSQL-Login/login.tf

Update Helm Release variables

---

modules/kubernetes/Manifest/manifest.tf
modules/kubernetes/Manifest/variables.tf

* Fix issue in `Manifest` module which required hard coded type setting for manifest objects

Update manifest generation method for Kubernetes objects

---

modules/vault/Kubernetes-Auth/versions.tf
modules/vault/Kubernetes-Secret/versions.tf
modules/vault/Vault-AppRole-Auth-Backend-Role/versions.tf
modules/vault/Vault-Mount-PKI/variables.tf
modules/vault/Vault-Mount-PKI/vault-mount.tf
modules/vault/Vault-Mount-PKI/versions.tf
modules/vault/Vault-Mount/versions.tf
modules/vault/Vault-PKI-Secret-Backend-Certificate/certificate.tf
modules/vault/Vault-PKI-Secret-Backend-Certificate/outputs.tf
modules/vault/Vault-PKI-Secret-Backend-Certificate/variables.tf
modules/vault/Vault-PKI-Secret-Backend-Certificate/versions.tf
modules/vault/Vault-PKI-Secret-Backend-Role/role.tf
modules/vault/Vault-PKI-Secret-Backend-Role/variables.tf
modules/vault/Vault-PKI-Secret-Backend-Role/versions.tf
modules/vault/Vault-Policy/versions.tf

https://github.com/wso2-enterprise/choreo/issues/35953
$subject
Using Terraform IaC, the PKI artifacts are expected to be managed

Add Terraform Modules for managing HashiCorp Vault PKI artifacts 

---

modules/vault/Vault-Mount-PKI/outputs.tf
modules/vault/Vault-PKI-Secret-Backend-Role/outputs.tf
modules/vault/Vault-PKI-Secret-Backend-Role/role.tf
modules/vault/Vault-PKI-Secret-Backend-Role/variables.tf

https://github.com/wso2-enterprise/choreo/issues/35953
$subject
Using Terraform IaC, the PKI artifacts are expected to be managed

Improve Terraform Modules for managing HashiCorp Vault PKI artifacts
